AWS Release candidate
BirthdayResearch/StateRelayer pull request #50
Opened 2023-09-14 03:07 UTC by cuongquangnam

#### What this PR does / why we need it:

#### Additional comments?:

2023-09-20 06:09 UTC, chloezxyy commented
I saw that you're manually uploading the zipfile, but im not sure if we want to do that manually. Have to check with either @thedoublejay or @veralygit

2023-09-20 06:45 UTC, pierregee requested changes

2023-09-22 04:30 UTC, veralygit commented
there is 2 ways to go about this. Are you going to package up this code and the lambda function calls your code from the package on the ops side 

or are we looking to shifting the codes here to the the lambda function directly

2023-09-22 05:03 UTC, cuongquangnam commented
by shifting the codes to lambda function directly, you mean copy and paste the index.ts file to the lambda ? 

> there is 2 ways to go about this. Are you going to package up this code and the lambda function calls your code from the package on the ops side
> 
> or are we looking to shifting the codes here to the the lambda function directly

by shifting the codes to lambda function directly, you mean copy and paste index.ts to lambda?

2023-09-22 06:00 UTC, veralygit commented on README.md
haha need some enlightenment on why we need to zip the file

2023-09-28 02:21 UTC, closed without merging